name: RUM Integration End-to-End Tests with Fastly
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # every hour
    - cron:  '0 * * * *'

jobs:
  test-with-bigquery:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      testid: ${{ steps.store_id.outputs.id }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCLOUD_CRED_FILE }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Check gcloud CLI
      run: gcloud info && gcloud auth list && bq version

    - name: Install dependencies
      run: cd test/pw && npm ci

    - name: Set up NS mapping
      run: sudo echo "$(dig +short n.sni.global.fastly.net | head -n 1) rum.hlx.page" | sudo tee -a /etc/hosts

    - name: Try out NS mapping
      run: echo '/etc/hosts:' && sudo cat /etc/hosts && echo 'getent hosts rum.hlx.page' && getent hosts rum.hlx.page

    - name: Install Playwright Browsers
      run: cd test/pw && npx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: cd test/pw && npm run test

    - id: store_id
      run: echo "id=${GITHUB_RUN_ID}" >> "$GITHUB_OUTPUT"

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: test/pw/playwright-report/
        retention-days: 30

  check-coralogix:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: test-with-bigquery
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Sleep for 15 mins until the data is ready in Coralogix
        run: sleep 10
      - name: Retrieve and check job ID
        env:
          JOB_ID: ${{needs.test-with-bigquery.outputs.testid}}
        run:  if [[ "$JOB_ID" != "$GITHUB_RUN_ID" ]]; then false; fi
      - name: Check Coralogix for request record
        env:
          CORALOGIX_TOKEN: ${{ secrets.CORALOGIX_TOKEN }}
          JOB_ID: ${{needs.test-with-bigquery.outputs.testid}}
        run: npm t
