name: Playwright E2E Tests
on: workflow_dispatch

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCLOUD_CRED_FILE }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    # - name: Install Google Bigquery CLI
    #   run: sudo apt-get install google-cloud-cli
    # - name: Authenticate with Google Cloud
    #   env:
    #     GCLOUD_CRED_FILE: ${{ secrets.GCLOUD_CRED_FILE }}
    #   run: echo $GCLOUD_CRED_FILE > ./gcloud.json && gcloud auth login --cred-file=./gcloud.json && gcloud config set project helix-225321 ; rm ./gcloud.json
    - name: Install dependencies
      run: cd test/pw && npm ci

    - name: Install Playwright Browsers
      run: cd test/pw && npx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: cd test/pw && gcloud auth list && bq version && npm run test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: test/pw/playwright-report/
        retention-days: 30
