name: RUM Integration End-to-End Tests
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # every hour
    - cron:  '0 * * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCLOUD_CRED_FILE }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Check gcloud CLI
      run: gcloud info && gcloud auth list && bq version

    - name: Install dependencies
      run: cd test/pw && npm ci

    - name: Try out NS mapping
      run: sudo echo $(dig +short n.sni.global.fastly.net.) www.blah.bla >> /etc/hosts && nslookup www.blah.bla && cat /etc/hosts

    - name: Install Playwright Browsers
      run: cd test/pw && npx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: cd test/pw && npm run test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: test/pw/playwright-report/
        retention-days: 30
