name: Fastly RUM Integration End-to-End Tests

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/test-common.yaml
    with:
      worker: FASTLY
    secrets: inherit
