name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string


jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - id: echo_config_path
      name: Echo config path
      run: echo "config_path=${{ inputs.config-path }}"

    - id: select_worker
      name: Select worker to use for RUM-collector
      run: echo "worker=`./src/scripts/select-worker.sh ${GITHUB_RUN_ID}`" >> "$GITHUB_OUTPUT"
