name: Fastly worker Optel End-to-End Tests

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 14:45 UTC on Monday to Thursday
    - cron:  '45 14 * * 1-4'

jobs:
  fastly:
    uses: ./.github/workflows/test-common.yaml
    with:
      worker: FASTLY
    secrets: inherit
